spring:
  application:
    name: ms-client

  datasource:
    url: jdbc:mysql://localhost:3306/ms_client_db
    username: root
    password: sasa
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
